version: '3.7'

volumes:
  data-volume:
services:
  api:
    build: .
    ports:
    - 8080
    depends_on:
    - db
  db:
    container_name: $DATABASE_TYPE
    image: $DATABASE_TYPE # postgres or mongo
    ports:
    - $DATABASE_PORT
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      PGDATA: /data/$DATABASE_TYPE
    volumes:
    - data-volume:/data/db

